/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {
        Thread myThread = new Thread(()->{
            for (int i = 0; i < 10; i++) {
                
                System.out.println("Inside the thread");
            }
        });
        myThread.setName("Reza");
        myThread.setPriority(Thread.MAX_PRIORITY);
        Thread.currentThread().setPriority(Thread.MIN_PRIORITY);
        System.out.println("Befor thread " + myThread.getName());
        myThread.start();
        Thread.yield();
        for (int i = 0; i < 10; i++) {
            
            System.out.println("After thread " + myThread.getName());
        }
    }
}
